amlogic: add u-boot update function to emmctool

diff --git a/projects/Amlogic/filesystem/usr/bin/emmctool b/projects/Amlogic/filesystem/usr/bin/emmctool
--- a/projects/Amlogic/filesystem/usr/bin/emmctool
+++ b/projects/Amlogic/filesystem/usr/bin/emmctool
@@ -152,6 +152,18 @@ do_write(){
   fi
 }
 
+do_uboot(){
+  do_umount
+  if [ "${2:0:10}" == "u-boot.bin" ]; then
+    echo "info: writing ${2} to ${EMMC}"
+    dd if="${2}" of="${EMMC}" conv=fsync,notrunc bs=1 count=444
+    dd if="${2}" of="${EMMC}" conv=fsync,notrunc bs=512 skip=1 seek=1
+  else
+    echo "error: ${2} is not a valid u-boot.bin* file!"
+    exit 1
+  fi
+}
+
 do_zero(){
   do_umount
   echo "info: zeroing ${EMMC}, be patient, this will take time"
@@ -168,6 +180,7 @@ do_help(){
   echo "                (l)abels             : change eMMC disk labels to ${BOOTLABEL}/${DISKLABEL}"
   echo "                (r)esize             : resize the storage partition to 100%"
   echo "                (s)storage           : convert emmc for use as /storage (boot from sdcard)"
+  echo "                (u)boot <filename>   : write signed u-boot <filename> to the eMMC module"
   echo "                (z)ero               : zero (erase/wipe) the eMMC module"
   echo "                (h)elp               : displays this help message"
   echo ""
@@ -182,7 +195,7 @@ if [ -z "${EMMC}" ]; then
 fi
 
 case $(dtname) in
-  friendlyarm*|hardkernel*|khadas*|libretech*|wetek*)
+  azw*|friendlyarm*|hardkernel*|khadas*|libretech*|wetek*)
     if [ "${BOOT}" = "${EMMC}" ]; then
       do_info
       echo "Your device is booted from the eMMC module!"
@@ -215,6 +228,9 @@ case "${1}" in
     ;;
   storage|s)
     do_storage "$@"
+    ;;
+  uboot|u)
+    do_uboot "$@"
     ;;
   write|w)
     do_write "$@"
